app/foodshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls')),
    path('orderlist/', include('orderlist.urls')),
    path('', include('shop.urls')),
    path('account/', include('account.urls')),
    path('promocode/', include('promocode.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/orderlist/urls.py
from django.urls import path
from . import views

app_name = 'orderlist'

urlpatterns = [
    path('', views.orderlist_detail, name='orderlist_detail'),
    path('add/<int:product_id>/', views.orderlist_add, name='orderlist_add'),
    path('delete/<int:product_id>/', views.orderlist_delete, name='orderlist_delete'),
]

app/shop/urls.py
from django.urls import path, include

from django.urls import path
from . import views

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('restaurant/<slug:shop_slug>/', views.product_list, name='product_list_by_shop'),
    # path('restaurant/<slug:shop_slug>/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('restaurant/product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

    # path('category/<slug:category_slug>/', views.product_list, name='product_category'),
]

app/shop/models.py
from django.conf import settings
from django.db import models
from django.db.models import Avg
from django.template.defaultfilters import slugify
from django.urls import reverse


RATING_CHOICES = [
    (1, "1 - Very bad"),
    (2, "2 - Bad"),
    (3, "3 - Okay"),
    (4, "4 - Great"),
    (5, "5 - Excellent"),
]


class Shop(models.Model):
    owner = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        default_related_name = "shop"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Shop, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        default_related_name = "category"
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class ProductQuerySet(models.query.QuerySet):

    def available(self):
        return self.filter(available=True)

    def non_available(self):
        return self.filter(available=False)


class ProductManager(models.Manager):

    def get_query_set(self):
        return ProductQuerySet(self.model)

    def available(self):
        return self.get_query_set().available()

    def non_available(self):
        return self.get_query_set().non_available()


class Product(models.Model):
    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, db_index=True)
    image = models.ImageField(upload_to='image_products/%Y/%m/%d', default='image_products/no_img.png')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ProductManager()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)
        default_related_name = "products"

    def get_absolute_url(self):
        return reverse('product_detail',
                       args=[self.id, self.slug])

    def get_shop_slug(self):
        shop = Shop.objects.get(name=self.shop)
        shop = shop.slug
        return reverse('product_list_by_shop',
                       args=[shop])

    def get_rating(self):
        product = Product.objects.get(id=self.id, slug=self.slug)
        rating = product.reviews.filter(show=True).aggregate(Avg('rating'))
        return rating

    def get_rating_votes(self):
        product = Product.objects.get(id=self.id, slug=self.slug)
        count = product.reviews.filter(show=True).count()
        return count

    def __str__(self):
        return self.name


class Reviews(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES, null=True, blank=True)
    body = models.TextField()
    show = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)
        verbose_name = "Review"
        verbose_name_plural = "Reviews"

    def __str__(self):
        return "Review №{} for {}".format(self.id, self.product)


class ReviewsAnswer(models.Model):
    review = models.ForeignKey(Reviews, on_delete=models.CASCADE, related_name='answers')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default='admin')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return "Answer on {}".format(self.review)

app/shop/forms.py
from django import forms
from .models import Reviews


class ReviewsForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['rating', 'body']
        labels = {
            'body': "Your review",
            'rating': "Your rating",
        }

app/shop/views.py
from django.contrib import messages
from django.db.models import Avg
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from foodshop.settings import LOGIN_URL
from .forms import ReviewsForm
from .models import Product, Category, Shop, Reviews, ReviewsAnswer
from orderlist.forms import OrderListAddProductForm
from .filters import ProductFilter


# class ProductListView(ListView):
#     context_object_name = 'product_list'
#     queryset = Product.objects.available()
#     template_name = 'shop/index.html'
#
#     def get_context_data(self, **kwargs):
#         context = super(ProductListView, self).get_context_data(**kwargs)
#         context['categories'] = Category.objects.all()
#         return context

def product_list(request, shop_slug=None, category_slug=None):
    orderlist_form = OrderListAddProductForm()
    shop = None
    shops = Shop.objects.all()
    category = None
    categories = Category.objects.all()
    products = Product.objects.available()
    products_non = Product.objects.non_available()
    if shop_slug:
        shop = Shop.objects.get(slug=shop_slug)
        products = products.filter(shop=shop)
        products_non = products_non.filter(shop=shop)
    if category_slug:
        category = Category.objects.get(slug=category_slug)
        products = products.filter(category=category)
        products_non = products_non.filter(category=category)
    products = products | products_non
    products = products.order_by('-available', '-created')
    myFilter = ProductFilter(request.GET, queryset=products)
    products = myFilter.qs
    paginator = Paginator(products, 12)
    page = request.GET.get('page')
    try:
        objects = paginator.page(page)
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)
    return render(request, 'shop/index.html',
                  {'product_list': objects,
                   'category': category,
                   'categories': categories,
                   'shop': shop,
                   'shops': shops,
                   "form": orderlist_form,
                   'myFilter': myFilter})


def product_detail(request, id, slug):
    product = Product.objects.get(id=id, slug=slug)
    orderlist_form = OrderListAddProductForm()
    reviews = product.reviews.filter(show=True)
    answers = ReviewsAnswer.objects.filter(review__in=reviews)
    paginator = Paginator(reviews, 5)
    page = request.GET.get('page')
    try:
        objects = paginator.page(page)
    except PageNotAnInteger:
        objects = paginator.page(1)
    except EmptyPage:
        objects = paginator.page(paginator.num_pages)
    new_review = None
    if request.method == "POST":
        reviews_form = ReviewsForm(request.POST)
        if reviews_form.is_valid() and request.user.is_authenticated:
            new_review = reviews_form.save(commit=False)
            new_review.product = product
            new_review.author = request.user
            new_review.save()
            reviews_form = ReviewsForm()
            messages.success(request, 'Your review has been successfully submitted for review')
            return HttpResponseRedirect(request.path)
        else:
            return redirect(LOGIN_URL)
    else:
        reviews_form = ReviewsForm()
    return render(request, 'shop/product_detail.html',
                  {'product': product,
                   'orderlist_form': orderlist_form,
                   'reviews': objects,
                   'answers': answers,
                   'new_review': new_review,
                   'reviews_form': reviews_form})

app/templates/shop/base.html
{% load custom_tags %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static '/categories-slider/splide-2.4.21/dist/css/splide.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/categories-slider/style.css' %}">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'product_list' %}">FoodShop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">&#9990; +380123456789<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">&#9993; support@gmail.com</a>
      </li>
    </ul>
      <span class="user">
        {% if request.user.is_authenticated %}
          Hello <a href="{% url 'edit' %}">{{ request.user.username }},</a>
          <a href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a href="{% url 'login' %}">Log-in</a>
        {% endif %}
    </span>
  </div>
</nav>
{% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <li class="{{ message.tags }}" >
          {{ message|safe }}
            <a href="#" class="close">x</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
<div id="subheader">
<div class="my-products">
    {% if request.user.is_authenticated %}
        {% if request.user|has_group:"entrepreneur" %}
            <a href="{% url 'my_products' %}">My products</a>
        {% endif %}
    {% endif %}
</div>
 <div class="order-list">
          {% with total_items=orderlist|length %}
            {% if orderlist|length > 0 %}
                Your order list contains:
                <a href="{% url 'orderlist:orderlist_detail' %}">
                    {{ total_items }} item{{ total_items|pluralize }},
                    ₴{{ orderlist.get_total_price }}
                </a>
            {% else %}
                Your order list is empty.
            {% endif %}
        {% endwith %}
      </div>
 </div>
{% block context %}
{% endblock context %}
{% load static %}
</body>

<script>
	document.addEventListener( 'DOMContentLoaded', function () {
        new Splide( '.splide', {
            fixedWidth: 120,
            rewind    : true,
            gap       : 5,
            pagination: false,
            perPage: 3,
            type: 'loop',
	    }).mount();
	});
</script>

<script src="{% static '/categories-slider/splide-2.4.21/dist/js/splide.min.js' %}"></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

app/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static %}
{% load custom_tags %}
<html>
<head>
</head>
{% block context %}
<body>
{% if categories %}
<div class="splide mb-3">
        <div class="splide__track">
            <ul class="splide__list">
                <li class="splide__slide"><a href="{{ request.path }}">All</a></li>
                {% for c in categories %}
                <li class="splide__slide"><a href="{{ request.path }}?category={{ c.id }}">{{ c.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endif %}
<form method="get">
    {{ myFilter.form.non_field_errors }}
    <div class="d-flex flex-row-reverse justify-content-between align-items-center mx-4">
        <div class="d-flex">
            {{ myFilter.form.price_start.errors }}
            {{ myFilter.form.price_end.errors }}
            <div class="filter-input d-flex align-items-center filter-price search-input-price">
                <label for="{{ myFilter.form.price_start.id_for_label }}">Price Range:</label>
                {{ myFilter.form.price_start }} {{ myFilter.form.price_end }}
            </div>
            <button class="btn btn-primary" type="submit">Filter</button>
        </div>
        <div class="d-flex align-items-center">
            {{ myFilter.form.name.errors }}
            <label for="{{ myFilter.form.name.id_for_label }}">Search:</label>
            <div class="filter-input search-input">{{ myFilter.form.name }}</div>
            <button class="btn btn-outline-primary ml-2" type="submit">Search</button>
        </div>
        <div>
            {{ myFilter.form.ordering.errors }}
            <label for="{{ myFilter.form.ordering.id_for_label }}">Ordering:</label>
            {{ myFilter.form.ordering }}
        </div>
    </div>
</form>
<div id="sidebar">
        <h3>Restaurants</h3>
        <ul>
            <li {% if not shop %} class="selected"{% endif %}>
                <a href="{% url 'product_list' %}">All</a>
            </li>
            {% for c in shops %}
                <li {% if shop.slug == c.slug %} class="selected"{% endif %}>
                    <a href="{% url 'product_list_by_shop' c.slug%}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
<div class="d-flex flex-column" style="margin-right: -5px;">
{% if product_list %}
<div class="row" style="margin-right: 5px">
      {% for product in product_list %}
        <div class="post-item col-12 col-sm-6 col-md-6 col-lg-3 p-2">
          <div class="card h-100 card-product align-items-center {% if not product.available %} gray-bg {% endif %}">
            <div class="card-body card-flex">
              <div class="product-image mb-2">
                <img src="{{ product.image.url }}">
              </div>
              <h2 class="card-title">{{ product.name }}</h2>
              <p class="text-primary"><i class="far fa-calendar-alt"></i>₴{{ product.price}}</p>
              <p class="card-text">{{product.category|safe | truncatewords:10 }}</p>
              <p class="card-text"><a href="{{ product.get_shop_slug }}">
                  {{product.shop|safe | truncatewords:10 }}</a></p>
              <p class="card-text">{% if product.get_rating.rating__avg %}
                  Rated at {{ product.get_rating.rating__avg }}/5.0 ({{ product.get_rating_votes }})
                                    {% else %}Not yet rated{% endif %}</p>
              {% if product.available %}
              <div class="d-flex justify-content-between">
              <a href="{{ product.get_absolute_url }}" style="width:50%; margin-right: 5px" class="btn btn-outline-primary">Read More</a>
              <a href="javascript:;" onclick="document.getElementById('product-add-{{ product.id }}').submit();"
                                                                   style="width: 50%" class="btn btn-outline-primary">Buy</a>
                <form id="product-add-{{ product.id }}" class="hidden"
                                                action="{% url 'orderlist:orderlist_add' product.id %}" method="post">
                    {{ form }}
                    {% csrf_token %}
                </form>
              {% else %}
                <p class="card-text" style="text-align: center; font-size: 20px; font-weight: 600">Non available</p>
              {% endif %}
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    {% if product_list %}
    {% include 'pagination/pagination.html' with page=product_list %}
    {% endif %}
    </div>
{% else %}
<p style="font-style:oblique; font-size: 400%">Sorry, there are no products in this collection.</p>
{% endif %}
</body>
</html>

{% endblock context %}

app/templates/shop/product_detail.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}{{ object.name }}{% endblock %}

{% block script %}
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
{% endblock %}

{% block context %}
  <div class="product-detail">
    <img src="{{ product.image.url }}">
    <h1>{{ product.name }}</h1>
    <h2>{{ product.category }}</h2>
    {% if product.get_rating.rating__avg %}<h2>Rated at {{ product.get_rating.rating__avg }}/5.0
                                                        ({{ product.get_rating_votes }})</h2>{% else %}
        <h2>Not yet rated</h2>{% endif %}
    <h2><a href="{{ product.get_shop_slug }}">{{ product.shop }}</a></h2>
    <p class="price">₴{{ product.price }}</p>
    <form action="{% url 'orderlist:orderlist_add' product.id %}" method="post">
    {{ orderlist_form }}
    {% csrf_token %}
    <input type="submit" value="Buy">
</form>
      <div class="product-description pl-2" style="word-wrap: break-word">
          {{ product.description}}
      </div>
  </div>
<div class="reviews mt-5 pl-2">
<h2>Reviews</h2>
    <hr />
    <button class="btn btn-primary" id="SendBtn" onclick="showFormReview()">Add review</button><hr />
    <div id="hidden-div" class="d-none">
      <div class="card card-body mt-2">
        <form action="." id="form-review" class="d-none" method="post">
            {{ reviews_form.as_p }}
            {% csrf_token %}
            <p><button class="btn btn-primary" type="submit">Send review</button></p>
        </form>
      </div>
    </div>
    <div class="reviews-list pb-2">
        {% if reviews %}
        {% for review in reviews %}
            <div>
                <p>
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    </svg>
                <b>{{ review.author }}:</b> {{ review.body }}

                {% for answer in answers %}
                    {% if answer.review_id == review.id %}
                        <br /><b>Answer:</b> <br />
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                            </svg>
                        <b>{{ answer.author }}:</b> {{ answer.body }}
                        </p>
                    {% endif %}
                {% endfor %}
                <hr>
            </div>
        {% endfor %}
        {% else %}
            <span style="font-size: 26px; font-weight: 600; font-style: italic">Sorry, there are no reviews here yet</span>
        {% endif %}
    </div>
</div>
    {% if reviews %}
    {% include 'pagination/pagination.html' with page=reviews %}
    {% endif %}
{% endblock %}