app/foodshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls')),
    path('orderlist/', include('orderlist.urls')),
    path('', include('shop.urls')),
    path('account/', include('account.urls')),
    path('promocode/', include('promocode.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/orderlist/urls.py
from django.urls import path
from . import views

app_name = 'orderlist'

urlpatterns = [
    path('', views.orderlist_detail, name='orderlist_detail'),
    path('add/<int:product_id>/', views.orderlist_add, name='orderlist_add'),
    path('delete/<int:product_id>/', views.orderlist_delete, name='orderlist_delete'),
]

app/shop/urls.py
from django.urls import path, include

from django.urls import path
from . import views

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('restaurant/<slug:shop_slug>/', views.product_list, name='product_list_by_shop'),
    # path('restaurant/<slug:shop_slug>/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('restaurant/product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

    # path('category/<slug:category_slug>/', views.product_list, name='product_category'),
]

app/orderlist/models.py
from django.db import models

# Create your models here.

app/orderlist/forms.py
from django import forms

PRODUCT_COUNT_CHOICES = [(i, str(i)) for i in range(1, 21)]


class OrderListAddProductForm(forms.Form):
    count = forms.TypedChoiceField(choices=PRODUCT_COUNT_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

app/orderlist/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST

from promocode.forms import PromocodeForm
from .forms import OrderListAddProductForm
from .orderlist import OrderList
from shop.models import Product


@require_POST
def orderlist_add(request, product_id):
    orderlist = OrderList(request)
    product = Product.objects.get(id=product_id)
    form = OrderListAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        orderlist.add(product=product,
                      count=cd['count'],
                      update_count=cd['update'])
    return redirect('orderlist:orderlist_detail')


def orderlist_delete(request, product_id):
    ordelist = OrderList(request)
    product = Product.objects.get(id=product_id)
    ordelist.delete(product)
    return redirect('orderlist:orderlist_detail')


def orderlist_detail(request):
    orderlist = OrderList(request)
    for item in orderlist:
        item['update_count'] = OrderListAddProductForm(
                            initial={'count': item['count'],
                                     'update': True})
    form = PromocodeForm()
    return render(request, 'orderlist/detail.html', {'orderlist': orderlist, "form": form})

app/templates/orderlist/detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% block title %}
    Order list
{% endblock %}
{% block context %}
    <h1>Your order list contains</h1>
    <table class="order-list">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Unit price</th>
            <th>Quantity</th>
            <th>Price</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for item in orderlist %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{{ product.image.url }}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td class="num">₴{{ item.price }}</td>
                    <td>
                        <form action="{% url 'orderlist:orderlist_add' product.id %}" method="post">
                            {{ item.update_count.count }}
                            {{ item.update_count.update }}
                            <input class="order-list" type="submit" value="Update">
                            {% csrf_token %}
                        </form>
                    </td>
                    <td class="num">₴{{ item.total_price }}</td>
                    <td><a class="order-list" href="{% url 'orderlist:orderlist_delete' product.id%}">Delete</a></td>
                </tr>
            {% endwith %}
        {% endfor %}
        {% if orderlist.promocode %}
            <tr class="subtotal">
                <td>Total sum without discount</td>
                <td colspan="3"></td>
                <td class="num">₴{{ orderlist.get_total_price}}</td>
                <td colspan="1"></td>
            </tr>
            <tr>
                <td>
                    Promocode "{{ orderlist.promocode.code }}"
                    ({{ orderlist.promocode.discount }}% off)
                </td>
                <td colspan="3"></td>
                <td class="num neg">
                    ₴{{ orderlist.get_discount|floatformat:"2" }}
                </td>
                <td colspan="1"></td>
            </tr>
        {% endif %}
        <tr class="total-sum">
            {% if orderlist.promocode %}
            <td>Total sum with discount</td>
            {% else %}
            <td>Total sum</td>
            {% endif %}
            <td colspan="4"></td>
            <td class="num">
                ₴{{ orderlist.get_total_price_discount|floatformat:"2" }}
            </td>
        </tr>
        </tbody>
    </table>
    <form style="margin-left: 10px" action="{% url "promocode_apply" %}" method="post">
        <p>Enter the promocode:</p>
        {{ form }}
    <input type="submit" value="Apply">
        {% csrf_token %}
    </form>
    <p class="text-right">
{#        <a href="{{ request.path }}" class="button light">Continue shopping</a>#}
        <a href="{{ request.META.HTTP_REFERER }}" class="button light">Continue shopping</a>
        <a href="{% url 'create_order' %}" class="button">Checkout</a>
    </p>
{% endblock %}